#!/usr/bin/env python3
"""Generate context/tables/<model>.md from the dbt repo's mart docs.

Usage:
    python3 scripts/sync_dbt_docs.py /path/to/ForaTravel/dbt

Rewrites only the block between the BEGIN/END dbt markers in each file, so
hand-written notes below the block are kept. Rerun whenever dbt docs change.
"""
import re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "context" / "tables"
BEGIN, END = "<!-- BEGIN dbt (generated by scripts/sync_dbt_docs.py; do not edit) -->", "<!-- END dbt -->"
DATASET = "data-warehouse-359101.analytics"


def parse(path):
    """Minimal parser for dbt model yml: models -> description + columns."""
    models, model, col, field, buf = [], None, None, None, []

    def flush():
        nonlocal buf, field
        if field and buf:
            text = " ".join(s.strip() for s in buf).strip().strip('"').strip("'")
            target = col if col is not None else model
            if target is not None:
                target[field] = text
        buf, field = [], None

    for line in path.read_text().splitlines():
        if m := re.match(r"^  - name: (\S+)", line):
            flush(); col = None
            model = {"name": m.group(1), "description": "", "columns": []}; models.append(model)
        elif model and (m := re.match(r"^      - name: (\S+)", line)):
            flush(); col = {"name": m.group(1), "description": ""}; model["columns"].append(col)
        elif model and (m := re.match(r"^( {4}| {8})description:\s*[>|]?-?\s*(.*)$", line)):
            flush()
            if len(m.group(1)) == 4:
                col = None
            field, buf = "description", [m.group(2)] if m.group(2) else []
        elif field and line.startswith(" " * 6) and not re.match(r"^\s+\w+:\s", line.strip() and line or "x: "):
            buf.append(line)
        elif field and line.strip() and not line.strip().startswith(("tests", "- ", "data_tests", "config", "meta", "constraints")):
            if re.match(r"^\s+[a-z_]+:", line):
                flush()
            else:
                buf.append(line)
        else:
            flush()
    flush()
    return models


def render(m, area):
    clean = lambda s: s.replace("|", "\\|").replace("\n", " ")
    lines = [BEGIN, f"# {m['name']}", "",
             f"`{DATASET}.{m['name']}` · dbt area: `{area}`", "",
             clean(m["description"]) or "_No dbt description._", ""]
    if m["columns"]:
        lines += ["| Column | Description |", "|---|---|"]
        lines += [f"| `{c['name']}` | {clean(c['description'])} |" for c in m["columns"]]
    lines += ["", END]
    return "\n".join(lines)


def main():
    dbt = Path(sys.argv[1] if len(sys.argv) > 1 else "../dbt")
    files = sorted((dbt / "models" / "3_marts").glob("*/_*.yml"))
    if not files:
        sys.exit(f"No mart yml files under {dbt}/models/3_marts")
    OUT.mkdir(parents=True, exist_ok=True)
    n = 0
    for f in files:
        for m in parse(f):
            if "DEPRECATED" in m["description"]:
                continue
            p = OUT / f"{m['name']}.md"
            block = render(m, f.parent.name)
            if p.exists() and BEGIN in (old := p.read_text()):
                text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, old, flags=re.S)
            else:
                text = block + "\n\n## Notes from analysts\n\n_Gotchas, common joins, and known issues. Hand-written; kept across syncs._\n"
            p.write_text(text); n += 1
    print(f"wrote {n} table docs to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
